apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"frontend","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"frontend","app.kubernetes.io/part-of":"opentelemetry-demo","app.kubernetes.io/version":"2.0.2","argocd.argoproj.io/instance":"dev-platform-tag-o11y-otel-demo","department":"RD","domain":"platform","env":"dev","helm.sh/chart":"opentelemetry-demo-0.37.7","opentelemetry.io/name":"frontend","owner":"tag-o11y","product":"C04KGSFF407","team":"tag-o11y"},"name":"frontend","namespace":"otel-demo"},"spec":{"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"opentelemetry.io/name":"frontend"}},"template":{"metadata":{"labels":{"app.kubernetes.io/component":"frontend","app.kubernetes.io/name":"frontend","opentelemetry.io/name":"frontend"}},"spec":{"containers":[{"env":[{"name":"OTEL_SERVICE_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.labels['app.kubernetes.io/component']"}}},{"name":"OTEL_COLLECTOR_NAME","value":"otel-collector"},{"name":"OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE","value":"cumulative"},{"name":"IPV6_ENABLED","value":"true"},{"name":"FRONTEND_PORT","value":"8080"},{"name":"FRONTEND_ADDR","value":":8080"},{"name":"AD_ADDR","value":"ad:8080"},{"name":"CART_ADDR","value":"cart:8080"},{"name":"CHECKOUT_ADDR","value":"checkout:8080"},{"name":"CURRENCY_ADDR","value":"currency:8080"},{"name":"PRODUCT_CATALOG_ADDR","value":"product-catalog:8080"},{"name":"RECOMMENDATION_ADDR","value":"recommendation:8080"},{"name":"SHIPPING_ADDR","value":"shipping:8080"},{"name":"FLAGD_HOST","value":"flagd"},{"name":"FLAGD_PORT","value":"8013"},{"name":"OTEL_COLLECTOR_HOST","value":"$(OTEL_COLLECTOR_NAME)"},{"name":"OTEL_EXPORTER_OTLP_ENDPOINT","value":"http://$(OTEL_COLLECTOR_NAME):4317"},{"name":"WEB_OTEL_SERVICE_NAME","value":"frontend-web"},{"name":"PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT","value":"http://localhost:8080/otlp-http/v1/traces"},{"name":"OTEL_RESOURCE_ATTRIBUTES","value":"service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=2.0.2"}],"image":"471112665254.dkr.ecr.us-east-1.amazonaws.com/github/open-telemetry/demo:2.0.2-frontend@sha256:3a0c7649f63d59656f6ba76fcd7ec79c1974cc3db0ae624efdf38fbdc8a14d4c","imagePullPolicy":"IfNotPresent","name":"frontend","ports":[{"containerPort":8080,"name":"service"}],"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"50m","memory":"128Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"runAsGroup":1001,"runAsNonRoot":true,"runAsUser":1001,"seccompProfile":{"type":"RuntimeDefault"}},"volumeMounts":null}],"serviceAccountName":"my-otel-demo","volumes":null}}}}
  creationTimestamp: "2025-09-11T21:48:42Z"
  generation: 5
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/version: 2.0.2
    argocd.argoproj.io/instance: dev-platform-tag-o11y-otel-demo
    department: RD
    domain: platform
    env: dev
    helm.sh/chart: opentelemetry-demo-0.37.7
    opentelemetry.io/name: frontend
    owner: tag-o11y
    product: C04KGSFF407
    team: tag-o11y
  name: frontend
  namespace: otel-demo
  resourceVersion: "750359011"
  uid: f39ea228-abae-4d6d-beb4-0ce7071a4b62
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      opentelemetry.io/name: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: frontend
        app.kubernetes.io/name: frontend
        opentelemetry.io/name: frontend
    spec:
      containers:
      - env:
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: OTEL_COLLECTOR_NAME
          value: otel-collector
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: cumulative
        - name: IPV6_ENABLED
          value: "true"
        - name: FRONTEND_PORT
          value: "8080"
        - name: FRONTEND_ADDR
          value: :8080
        - name: AD_ADDR
          value: ad:8080
        - name: CART_ADDR
          value: cart:8080
        - name: CHECKOUT_ADDR
          value: checkout:8080
        - name: CURRENCY_ADDR
          value: currency:8080
        - name: PRODUCT_CATALOG_ADDR
          value: product-catalog:8080
        - name: RECOMMENDATION_ADDR
          value: recommendation:8080
        - name: SHIPPING_ADDR
          value: shipping:8080
        - name: FLAGD_HOST
          value: flagd
        - name: FLAGD_PORT
          value: "8013"
        - name: OTEL_COLLECTOR_HOST
          value: $(OTEL_COLLECTOR_NAME)
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(OTEL_COLLECTOR_NAME):4317
        - name: WEB_OTEL_SERVICE_NAME
          value: frontend-web
        - name: PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://localhost:8080/otlp-http/v1/traces
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=2.0.2
        image: 471112665254.dkr.ecr.us-east-1.amazonaws.com/github/open-telemetry/demo:2.0.2-frontend@sha256:3a0c7649f63d59656f6ba76fcd7ec79c1974cc3db0ae624efdf38fbdc8a14d4c
        imagePullPolicy: Always
        name: frontend
        ports:
        - containerPort: 8080
          name: service
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: my-otel-demo
      serviceAccountName: my-otel-demo
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-09-11T21:48:43Z"
    lastUpdateTime: "2025-09-11T23:12:14Z"
    message: ReplicaSet "frontend-5fc76d8865" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-09-12T15:31:44Z"
    lastUpdateTime: "2025-09-12T15:31:44Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
